apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
<<<<<<< HEAD
    kompose.version: 1.24.0 (4a2a0458)
=======
    kompose.image-pull-policy: Never
    kompose.version: 1.25.0 (HEAD)
>>>>>>> 62cf1464c232b3162183f74587ffeca968afb34f
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
<<<<<<< HEAD
        kompose.version: 1.24.0 (4a2a0458)
=======
        kompose.image-pull-policy: Never
        kompose.version: 1.25.0 (HEAD)
>>>>>>> 62cf1464c232b3162183f74587ffeca968afb34f
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - image: backend
<<<<<<< HEAD
=======
          imagePullPolicy: Never
>>>>>>> 62cf1464c232b3162183f74587ffeca968afb34f
          name: backend
          ports:
            - containerPort: 80
          resources: {}
      hostname: backend
      restartPolicy: Always
status: {}
