apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: LoadBalancer
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 3001
  selector:
    io.kompose.service: backend
  type: LoadBalancer
status:
  loadBalancer: {}
