version: '3.8'

services:
  frontend:
    image: "frontend"
    hostname: "frontend"
    container_name: "frontend"
    build: ./client
    ports:
      - 8080:3000
  backend:
    image: "backend"
    hostname: "backend"
    container_name: "backend"
    build: ./server
    ports:
      - 5001:80
  database:
    image: mongo
    container_name: "dongo"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    volumes:
      - "./database:/data/db"
    restart: unless-stopped
