version: '3.8'

services:
  frontend:
    image: "frontend"
    hostname: "frontend"
    container_name: "frontend"
    build: ./client
    ports:
<<<<<<< HEAD
      - 8080:3000
=======
      - 8080:8080
    labels:
      kompose.service.type: LoadBalancer
      kompose.image-pull-policy: "Never"
>>>>>>> 62cf1464c232b3162183f74587ffeca968afb34f
  backend:
    image: "backend"
    hostname: "backend"
    container_name: "backend"
    build: ./server
    ports:
      - 5001:80
<<<<<<< HEAD
  database:
    image: mongo
    container_name: "dongo"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    volumes:
      - "./database:/data/db"
    restart: unless-stopped
=======
    labels:
      kompose.image-pull-policy: "Never"
>>>>>>> 62cf1464c232b3162183f74587ffeca968afb34f
